# Generated by Django 5.1.2 on 2025-03-26 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_limite", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("concluida", "Concluida"),
                            ("atrasada", "Atrasada"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("categoria", models.ManyToManyField(related_name="tarefas", to="core.categoria")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="tarefas", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
