# Generated by Django 5.1.7 on 2025-03-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_tarefa_icone"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="cor",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
