# Generated by Django 5.1.7 on 2025-03-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_user_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="imagem",
            field=models.ImageField(
                blank=True,
                help_text="Foto de perfil do usuário.",
                null=True,
                upload_to="users/",
                verbose_name="Imagem do usuário",
            ),
        ),
    ]
