# Generated by Django 5.2 on 2025-04-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_categoria_cor"),
        ("core", "0009_alter_user_imagem"),
    ]

    operations = []
