# Generated by Django 5.2 on 2025-04-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_merge_0008_categoria_cor_0009_alter_user_imagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="passage_id",
        ),
    ]
