# Generated by Django 5.1.2 on 2025-04-04 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_user_passage_id'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagem',
            field=models.ForeignKey(blank=True, default=None, help_text='Foto de perfil do usuário.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image', verbose_name='Imagem do usuário'),
        ),
    ]
