# Generated by Django 5.2 on 2025-04-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_user_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="categoria",
            field=models.ManyToManyField(blank=True, default=None, related_name="tarefas", to="core.categoria"),
        ),
    ]
